[build]
  command = "node scripts/netlify-build.mjs"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY = "true"
  UPLOAD_STORE = "blobs"
  APP_VERSION = "1.0.0"
  NPM_CONFIG_PRODUCTION = "false"
  NPM_FLAGS = "--include=optional"
  NODE_OPTIONS = "--max-old-space-size=4096"

[functions]
  included_files = ["node_modules/.prisma/**", "node_modules/@prisma/client/**"]
