ALTER TABLE "StoreTheme" ADD COLUMN IF NOT EXISTS "layoutMode" TEXT NOT NULL DEFAULT 'builtin';
ALTER TABLE "StoreTheme" ADD COLUMN IF NOT EXISTS "customHtml" TEXT;
ALTER TABLE "StoreTheme" ADD COLUMN IF NOT EXISTS "customCss" TEXT;
ALTER TABLE "StoreTheme" ADD COLUMN IF NOT EXISTS "customJs" TEXT;
ALTER TABLE "StoreTheme" ADD COLUMN IF NOT EXISTS "visualProfile" TEXT;
