import { notFound } from "next/navigation";

import { db } from "@/lib/db";
import { getStoreAccess } from "@/lib/seller/access";
import { formatMoney } from "@/lib/money";
import { PrintButton } from "@/components/seller/PrintButton";

export const metadata = { title: "Invoice" };

export default async function InvoicePage({
  params,
}: {
  params: Promise<{ storeId: string; orderId: string }>;
}) {
  const { storeId, orderId } = await params;
  const access = await getStoreAccess(storeId, "orders");
  if (!access) notFound();
  const { store } = access;

  const order = await db.order.findFirst({
    where: { id: orderId, storeId },
    include: { items: true, customerRef: true },
  });
  if (!order) notFound();

  return (
    <div className="mx-auto max-w-2xl bg-white p-10 text-black print:p-0" data-theme="light">
      <div className="mb-8 flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold">{store.name}</h1>
          {store.addressLine1 && (
            <p className="mt-1 text-sm text-gray-600">
              {store.addressLine1}
              {store.city ? `, ${store.city}` : ""}
              {store.postalCode ? ` ${store.postalCode}` : ""}
              {store.country ? `, ${store.country}` : ""}
            </p>
          )}
          {store.taxId && <p className="text-sm text-gray-600">Tax ID: {store.taxId}</p>}
          {store.businessEmail && (
            <p className="text-sm text-gray-600">{store.businessEmail}</p>
          )}
        </div>
        <PrintButton />
      </div>

      <div className="mb-8 flex justify-between">
        <div>
          <h2 className="text-lg font-semibold">Invoice #{order.orderNumber}</h2>
          <p className="text-sm text-gray-600">
            Date: {order.createdAt.toLocaleDateString("en-US", { dateStyle: "long" })}
          </p>
          <p className="text-sm text-gray-600">Status: {order.status}</p>
        </div>
        <div className="text-right">
          <h3 className="text-sm font-semibold uppercase text-gray-500">Bill to</h3>
          <p className="text-sm">{order.customerRef?.name ?? order.customerEmail}</p>
          <p className="text-sm text-gray-600">{order.customerEmail}</p>
        </div>
      </div>

      <table className="mb-6 w-full border-collapse text-sm">
        <thead>
          <tr className="border-b-2 border-black text-left">
            <th className="py-2">Item</th>
            <th className="py-2 text-right">Qty</th>
            <th className="py-2 text-right">Unit price</th>
            <th className="py-2 text-right">Amount</th>
          </tr>
        </thead>
        <tbody>
          {order.items.map((item) => (
            <tr key={item.id} className="border-b border-gray-200">
              <td className="py-2">
                {item.productName}
                {item.variantName && (
                  <span className="text-gray-500"> — {item.variantName}</span>
                )}
              </td>
              <td className="py-2 text-right">{item.quantity}</td>
              <td className="py-2 text-right">
                {formatMoney(item.unitPriceCents, order.currency)}
              </td>
              <td className="py-2 text-right">
                {formatMoney(item.unitPriceCents * item.quantity, order.currency)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="ml-auto w-64 text-sm">
        <div className="flex justify-between py-1">
          <span className="text-gray-600">Subtotal</span>
          <span>{formatMoney(order.subtotalCents, order.currency)}</span>
        </div>
        {order.discountCents > 0 && (
          <div className="flex justify-between py-1">
            <span className="text-gray-600">Discount</span>
            <span>−{formatMoney(order.discountCents, order.currency)}</span>
          </div>
        )}
        <div className="flex justify-between py-1">
          <span className="text-gray-600">Shipping</span>
          <span>{formatMoney(order.shippingCents, order.currency)}</span>
        </div>
        <div className="flex justify-between py-1">
          <span className="text-gray-600">
            Tax{store.taxRate ? ` (${store.taxRate}%)` : ""}
          </span>
          <span>{formatMoney(order.taxCents, order.currency)}</span>
        </div>
        <div className="mt-1 flex justify-between border-t-2 border-black py-2 font-bold">
          <span>Total</span>
          <span>{formatMoney(order.totalCents, order.currency)}</span>
        </div>
        {order.refundedCents > 0 && (
          <div className="flex justify-between py-1 text-red-600">
            <span>Refunded</span>
            <span>−{formatMoney(order.refundedCents, order.currency)}</span>
          </div>
        )}
      </div>

      <p className="mt-10 text-center text-xs text-gray-400">
        Generated by Foundry · {new Date().toLocaleDateString("en-US")}
      </p>
    </div>
  );
}
